name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: 14
      run: npm ci
      run: npm run lint
  tests:
    needs: linter
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: 14
      run: npm ci
      run: npm run test
  release:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: 14
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm ci
      run: npx semantic-release
